version: '3'

services:
  server:
    container_name: server_rest_template
    restart: always
    build: ./server
    ports:
      - '5000:5000'
    env_file:
      - '.env'
    links:
      - db
    volumes:
      - './server/src:/usr/src/server/src'

  db:
    container_name: db_rest_template
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - '.env'
